# Dockerfile for Bayota
#
# Files to exclude are listed in the ./dockerignore file
#
# Example commands...
#
#  Create a docker image:
#     >> docker build -f Dockerfile_36 --tag my-python-app .
#
#  Inspect the available docker images:
#     >> docker images
#
#  Delete/remove existing image <by Image ID> listed in "docker images"
#     >> docker rmi <ID>
#     >> docker rmi ef9a50d6e1a2

FROM python:alpine3.6

#FROM frolvlad/alpine-python3

RUN apk add --no-cache \
        --virtual=.build-dependencies \
        g++ gfortran file binutils \
        musl-dev python3-dev openblas-dev && \
    apk add libstdc++ openblas && \
    \
    ln -s locale.h /usr/include/xlocale.h && \
    \
    pip install -U pip && \
    \
    pip install numpy && \
    pip install pandas && \
    \
    rm -r /root/.cache && \
    find /usr/lib/python3.*/ -name 'tests' -exec rm -r '{}' + && \
    find /usr/lib/python3.*/site-packages/ -name '*.so' -print -exec sh -c 'file "{}" | grep -q "not stripped" && strip -s "{}"' \; && \
    \
    rm /usr/include/xlocale.h && \
    \
    apk del .build-dependencies

RUN apk update \
  && pip install -U pip \
  && apk add --no-cache --update-cache gcc gfortran libgfortran lapack-dev libexecinfo-dev \
  && apk add --no-cache --update-cache python3 python3-dev g++ \
  && apk add --no-cache --update-cache libgcc libc-dev libquadmath musl musl-dev

COPY ./efficiencysubproblem /app/efficiencysubproblem

WORKDIR /app/efficiencysubproblem

RUN python setup.py develop
### #CMD python ./index.py