# Dockerfile for Bayota
#
# Files to exclude are listed in the ./dockerignore file
#
# Example commands...
#
#  Create a docker image:
#     >> docker build -f Dockerfile_36_multistage --tag bayota_app .
#
#    -- Create a first-stage docker image from the 'builder' stage:
#       >> docker build -f Dockerfile_36_multistage --tag bayota_app_builder . --target builder
#    -- Create a second-stage docker image from the 'builder2' stage:
#       >> docker build -f Dockerfile_36_multistage --tag bayota_app_builder2 . --target builder2
#
#  Inspect the available docker images:
#     >> docker images
#
#  Run a docker image in interactive mode (to see file directory structure):
#     >> docker run -it <iamgeID> sh
#
#  Delete/remove existing image <by Image ID> listed in "docker images"
#     >> docker rmi <imageID>
#     >> docker rmi ef9a50d6e1a2
#
#
#  Test commands to pass to docker container:
#    -- Generate a model:
#     >> docker run -it <imageID> ./bin/scripts_by_level/run_generatemodel.py -g CalvertMD -n costmin_total_percentreduction -sf ~/bayota_ws_0.0a1.dev4/temp/model_instances/modelinstance_costmin_total_percentreduction_CalvertMD.pickle -bl 2010NoActionLoads.csv
#    -- Solve a model trial:
#     >> docker run -it <imageID> ./bin/scripts_by_level/run_conductexperiment.py -n /root/bayota/bin/run_specs/experiment_specs/costmin_1-40percentreduction -sf /root/bayota_ws_0.0a1.dev4/temp/model_instances/modelinstance_costmin_total_percentreduction_CalvertMD.pickle


# ######################################
# --- First-Stage Image: Build IPOPT ---
# ######################################
FROM python:alpine3.6 as builder

# --- Install basic requirements ---
RUN apk update \
  && apk add ca-certificates wget \
  && update-ca-certificates \
  && apk add --no-cache --update-cache curl gcc g++ gfortran patch

# --- Get the IPOPT code ---
WORKDIR /
RUN apk update \
    && curl --remote-name https://www.coin-or.org/download/source/Ipopt/Ipopt-3.12.11.tgz \
    \
    && tar -xvzf Ipopt-3.12.11.tgz \
    && mv /Ipopt-3.12.11 /CoinIpopt

# --- Download external code packages ---
RUN apk update \
    && cd /CoinIpopt/ThirdParty/Blas \
    \
    && ./get.Blas \
    && cd ../Lapack \
    && ./get.Lapack \
    && cd ../ASL \
    && ./get.ASL \
    && cd ../Mumps \
    && ./get.Mumps

# --- Run IPOPT configure script ---
RUN apk update \
    && mkdir /CoinIpopt/build \
    && cd /CoinIpopt/build \
    \
    && /CoinIpopt/configure

# --- Build the IPOPT code ---
RUN apk update \
    && apk add --update make \
    && cd /CoinIpopt/build \
    && make \
    && make test \
    && make install


# #################################################
# --- Second-Stage Image: Build python packages ---
# #################################################
FROM python:alpine3.6 as builder2
# Add the IPOPT directory generated in the `builder` container above
COPY --from=builder /CoinIpopt /CoinIpopt

# --- Install python math/science packages ---
RUN apk add --no-cache \
        --virtual=.build-dependencies \
        g++ gfortran file binutils \
        musl-dev openblas-dev \
        libpng-dev freetype-dev \
    && apk add libstdc++ openblas \
    \
    && ln -s locale.h /usr/include/xlocale.h \
    \
    && pip install -U pip \
    && pip install --upgrade setuptools \
    \
    && pip install numpy \
    && pip install pandas \
    && pip install matplotlib \
    \
    && rm /usr/include/xlocale.h \
    \
    && apk del .build-dependencies


# ########################################
# --- Third-Stage Image: Set up Bayota ---
# ########################################
FROM python:alpine3.6
# Add the IPOPT directory and python packages from `builder2` container above
COPY --from=builder2 /CoinIpopt /CoinIpopt
COPY --from=builder2 /root/.cache /root/.cache

# --- Update pip ---
RUN apk update \
    && pip install -U pip \
    && pip install --upgrade setuptools

# --- Install other requirements ---
RUN apk update \
    && apk add --no-cache --update-cache openblas \
    && apk add --no-cache --update-cache gcc gfortran libgfortran lapack-dev libexecinfo-dev \
    && apk add --no-cache --update-cache g++ libgcc libc-dev libquadmath musl musl-dev

# --- Set up Bayota ---
COPY . /root/bayota
WORKDIR /root/bayota

# RUN python setup.py develop
RUN pip install .