# Formatter constructors take two optional arguments: a message format string and a date format string.
#   So the formatters are lists of length 2
formatters:
  default: ['%(levelname)-8s %(message)s',
            '']
  console:
    info: ['%(levelname)-8s %(message)s',
           '']
    debug: ['%(levelname)-8s in <%(module)s>, line %(lineno)d - %(message)s',
            '']
  file:
    info: ["%(asctime)s %(levelname)-8s %(lineno)4d:%(module)-50s %(message)s",
             "%Y-%m-%d %H:%M:%S"]
    debug: ["%(asctime)s %(levelname)-8s %(lineno)4d:%(module)-50s %(message)s",
             "%Y-%m-%d %H:%M:%S"]
